# -*- coding: utf-8 -*-
"""Copy of Task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5epdR57n0SnOITSKkvUGAcWoJLsAdFx
"""

!pip install -q \
transformers==4.41.2 \
datasets==2.19.0 \
accelerate==0.30.1 \
huggingface_hub==0.23.0 \
peft==0.11.1

import transformers
import datasets
import huggingface_hub
import peft

print("transformers =", transformers.__version__)
print("datasets =", datasets.__version__)
print("hub =", huggingface_hub.__version__)
print("peft =", peft.__version__)

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

print("Model Loaded Successfully")

import pandas as pd

data = {
    "input": [
        "I am stressed about my exams",
        "I feel lonely",
        "I am anxious",
        "I had a bad day",
        "I feel overwhelmed",
        "I am sad",
        "Nobody understands me",
        "I feel nervous about my future"
    ],
    "response": [
        "I understand. Exams can be stressful. Try taking breaks and focusing on one topic at a time.",
        "I'm sorry you're feeling lonely. Would you like to talk about it?",
        "Anxiety can be difficult. Taking slow deep breaths may help.",
        "I'm sorry your day was difficult. Tomorrow is a new opportunity.",
        "It sounds like you have a lot on your mind. Take things one step at a time.",
        "I'm sorry you're feeling sad. Your feelings are important.",
        "That sounds painful. You deserve to be heard and understood.",
        "It's normal to feel uncertain about the future. Focus on what you can control today."
    ]
}

df = pd.DataFrame(data)
df

from datasets import Dataset

dataset = Dataset.from_pandas(df)

print(dataset)

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

tokenizer.pad_token = tokenizer.eos_token

print("Model Loaded Successfully")

def preprocess(example):

    text = f"User: {example['input']}\nBot: {example['response']}"

    tokens = tokenizer(
        text,
        truncation=True,
        padding="max_length",
        max_length=128
    )

    tokens["labels"] = tokens["input_ids"].copy()

    return tokens

print("Preprocessing Function Ready")

tokenized_dataset = dataset.map(preprocess)

print(tokenized_dataset)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./mental_health_bot",
    num_train_epochs=20,
    per_device_train_batch_size=2,
    logging_steps=1,
    save_strategy="no"
)

print("Training Arguments Ready")

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset
)

print("Trainer Ready")

trainer.train()

trainer.save_model("./mental_health_bot")
tokenizer.save_pretrained("./mental_health_bot")

print("Model Saved Successfully")

import torch

def chat(user_input):

    prompt = f"User: {user_input}\nBot:"

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    )

    outputs = model.generate(
        **inputs,
        max_length=80,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id
    )

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    return response

print("Chatbot Ready")

print(chat("I feel lonely"))

print(chat("I am stressed about exams"))